### ISSUE TITLE
Break up/refactor `geometry.jl` as it is currently very long

### ISSUE THREAD

**Issue by Cmurilochem** [fverdugo/GalerkinToolkit.jl#89]

**Comment by fverdugo** [comment]
To start with, we can split the sequential from the parallel code. This will convert file `geometry.jl` into two new files `mesh.jl` and `p_mesh.jl`.

**Comment by Cmurilochem** [comment]
Thanks @fverdugo. That is an excellent; I will soon come back to it, after dealing with some simpler tasks just to warm up.

**Comment by Cmurilochem** [comment]
> Thanks @fverdugo. That is an excellent; I will soon come back to it, after dealing with some simpler tasks just to warm up.



> To start with, we can split the sequential from the parallel code. This will convert file `geometry.jl` into two new files `mesh.jl` and `p_mesh.jl`. (and remove `geometry.jl`)

@fverdugo. I have a (naive) conceptual question that came out while addressing #93. This is relation to the way we want to deal with functions that are defined at "module" level or outside its scope. I have an example:

In `mesh.jl`, we have:

https://github.com/fverdugo/GalerkinToolkit.jl/blob/7a27676a61b94e24a277eb72bce6e5e0674ce1bc/src/mesh.jl#L3371-L3372

Two question arise from it:

1. The default value of `partition_strategy` is given by `GT.partition_strategy()`. However this function is uniquely defined above; [here](https://github.com/fverdugo/GalerkinToolkit.jl/blob/7a27676a61b94e24a277eb72bce6e5e0674ce1bc/src/mesh.jl#L3344). So, what is the point in using `GT.` ? This explicitly tells that this function is defined elsewhere. Or Am I missing something ? Note that this is coming from the original `geometry.jl`

2. `mesh_graph` is also called inside `p_mesh.jl`.  So, in this case, Should I call there `GT.mesh_graph(...)` since it is only defined outside the module, in `mesh.jl` ?

Sorry for perhaps being "picky" but I think this is important for code readability. Thanks!

**Comment by fverdugo** [comment]
I agree that qualifying function names with `GT.` is not necessary when working inside the module. NB. In some situations it is necessary if there is local variable that shadows the function name.

I have no strong feelings about if we should use `GT.` or not when it is redundant.  It is provably better to not use it as you say.

**Comment by Cmurilochem** [comment]
> I agree that qualifying function names with `GT.` is not necessary when working inside the module. NB. In some situations it is necessary if there is a local variable that shadows the function name.
> 
> I have no strong feelings about if we should use `GT.` or not when it is redundant. It is provably better to not use it as you say.

Thanks @fverdugo for clarifying this. I now understand why you use `GT.partition_strategy()` as right below there is a variable called `partition_strategy`. Agreed, I will follow your suggestion and keep it simple. Thanks!
